import {
  BOTTLE_WISHES,
  GLOWING,
  GROWTH,
  HARBOUR,
  KIND_INFO,
  KINDS,
  MIN_PIXELS,
  NEAR,
  PALETTE_CHARS,
  PALETTE_NAMES,
  SPRITE_PALETTE,
  SPRITE_SIZE,
  TRANSPARENT,
} from '@/features/island';
import { WISH_URL } from '@/shared/repo';

const NEAR_TEXT: Record<(typeof NEAR)[number], string> = {
  anywhere: 'wherever there is room',
  well: 'close to the wishing well, in the middle of things',
  water: 'close to the shore',
  quiet: 'as far from everything else as possible',
};

/** RULES.md – generated from the rule code, so the prose can never drift from what the routine enforces. */
export function renderRulesDoc(): string {
  const kinds = KINDS.map((k) => {
    const info = KIND_INFO[k];
    return `| **${info.label}** | ${info.rule} | ${info.examples} |`;
  });
  const palette = PALETTE_CHARS.map(
    (c) =>
      `| \`${c}\` | ${PALETTE_NAMES[c]} | \`${SPRITE_PALETTE[c]}\` | ${GLOWING.includes(c) ? 'glows at night' : ''} |`,
  );
  return [
    '# Rules of the island',
    '',
    '> Generated from `src/features/island/` – the code enforces every rule on this page; the daily routine only',
    '> chooses within them. Change the rules in code, then run `npm run world:render`.',
    '',
    '## How a wish comes true',
    '',
    `1. Anyone opens a [wish](${WISH_URL}): one thing for the island, a name, a line about it – and, if you like, a drawing.`,
    '2. Everyone can vote with a 👍 reaction on the issue.',
    '3. Every morning the routine grants the wish with the most 👍 (at least one) that fits the rules below. On a tie the older wish wins.',
    '4. The wish is drawn as a 16 × 16 sprite (yours, or Claude draws one from your words), placed on the island and',
    '   written into the logbook with your name. The issue is closed with a comment and you are credited as co-author of that day’s commit.',
    '5. A wish that does not fit *yet* stays open with a note saying what is missing – usually room. Every open wish shines as a star',
    '   above the island; the more 👍, the brighter.',
    '',
    '## One wish, one tile',
    '',
    'Every wish is one of six kinds. How many of a kind the island can hold grows with the island:',
    '',
    '| Kind | Where and how many | For example |',
    '|---|---|---|',
    ...kinds,
    '',
    `A wish can ask to stand somewhere: ${NEAR.map((n) => `**${n}** (${NEAR_TEXT[n]})`).join(', ')}. The exact tile is chosen by the code.`,
    '',
    '## The sea',
    '',
    `Every dawn the sea raises **${GROWTH.tiles} tiles** of shore, before the day's wish. Land with land on all four sides turns to grass,`,
    `the rest is beach – buildings and plants need grass. The sea keeps ${HARBOUR} tiles of open water around every boat or fish,`,
    'so no water wish is ever locked into a pond. Together the room for all kinds grows faster than one per tile, so the island never fills up.',
    '',
    '## Wishes that are declined',
    '',
    'A wish is closed without being granted when it asks for something that does not belong on a small, kind island: anything',
    'hurtful or violent, politics, real people, brands, logos or other trademarks, links or advertising. The routine says why in one friendly',
    'comment. Everything else simply waits its turn.',
    '',
    '## Messages in a bottle',
    '',
    `On a day when no wish fits, the islanders wish for something themselves – a lantern, a cat, a rowboat (${BOTTLE_WISHES.length} ideas in`,
    '`catalogue.ts`), or something Claude draws for them. The logbook marks these days as messages in a bottle.',
    '',
    '## Drawing a sprite',
    '',
    `A sprite is ${SPRITE_SIZE} lines of ${SPRITE_SIZE} characters. \`${TRANSPARENT}\` is transparent; every other character is one colour of the palette.`,
    `It needs at least ${MIN_PIXELS} coloured pixels and at least two colours (an outline and a fill), and it may not fill the whole tile.`,
    'Draw it standing on the bottom rows – the island is seen from above, the things on it from the front.',
    '',
    '| Character | Colour | Hex | |',
    '|---|---|---|---|',
    ...palette,
    '',
    'A lantern, for example:',
    '',
    '```text',
    '................',
    '.......kk.......',
    '......kyyk......',
    '.....kyccyk.....',
    '.....kyccyk.....',
    '.....kyccyk.....',
    '......kyyk......',
    '.......kk.......',
    '.......uu.......',
    '.......uu.......',
    '.......uu.......',
    '.......uu.......',
    '.......uu.......',
    '......uuuu......',
    '.....kkkkkk.....',
    '................',
    '```',
    '',
  ].join('\n');
}
